#!/bin/bash

CI_INIT_ADMIN=test-dev
CI_INIT_PASSWORD=arvato123

JENKINS_WEBURL=jenkins-master:8080/jenkins

SOURCE=`dirname "$0"`

CHANGEID=
CHANGEURL=
PROJECT=
BRANCH=
SUBMITTER=
COMMIT=
while [ $# -gt 0 ]
do
        case "$1" in
                (--change)     CHANGEID="$2";  shift ;;
                (--change-url) CHANGEURL="$2"; shift ;;
                (--change-owner)   OWNER="$2"; shift ;;
                (--project)    PROJECT="$2";   shift ;;
                (--branch)     BRANCH="$2";    shift ;;
                (--submitter)  SUBMITTER="$2"; shift ;;
                (--commit)     COMMIT="$2";    shift ;;
                (--newrev)     NEWREV="$2";    shift ;;
                (*)                            shift ;;
        esac
        shift
done
if [ "$PROJECT" != "All-Projects" ]; then
    cat ${SOURCE}/config.xml | sed -e 's/${PROJECT_NAME}/'${PROJECT}'/g' > config_temp.xml
    curl -XPOST ${JENKINS_WEBURL}/createItem?name=${PROJECT} -u ${CI_INIT_ADMIN}:${CI_INIT_PASSWORD} --data-binary @config_temp.xml -H "Content-Type:text/xml"
fi
